### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Goerni** [Microsoft/pxt-sonar#1]
Hi,
with the HC-SR04 ultrasonic distance sensor and the pxt.microbit,org editor for the BBC Microbit the Package don't work. 

The output is always "0". 

The hardware works fine (tested with an Arduino Uno)

Shure that this package should work? 

Best regards

**Comment by leomazzi** [comment]
HC-SR04 works with 5V, microbit works with 3V - are you powering the HC-SR04 with 5V and reducing the voltage on the "echo" output with resistors or other from 5V to 3V?

**Comment by Goerni** [comment]
No, i didn't. I'm sorry, thanks for the hint! ;) I will try this.

**Comment by Goerni** [comment]
So here is one with 3V (if any one is interessted)

http://www.ebay.de/itm/3V-5-5V-HC-SR04-Ultrasonic-Module-Distance-Measuring-Sensor-for-Arduino-UNO-MCU-/381496724507
